algonauts:
  params:
    tr: 1.49
    hrf_delay: 3
    context_trs: 5
    atlas_name: '1000Parcels_7Networks_order'
    num_parcels: 1000
    n_windows_per_task: 60

  subjects:
    - 1
    - 2
    - 3
    - 5

hcptrt:
  params:
    tr: 1.49
    hrf_delay: 3
    context_trs: 5
    parcellation: 'ca_parcels'
    n_windows_per_task: 60
  
  subjects:
    - 1

  sessions:
    - 1

  tasks:
    - motor
    - gambling
    - wm
    - restingstate
    - social
    - emotion
    - language
    - relational