import streamlit as st

st.title("Progress Report")

st.markdown("---")

st.header("Methodology")

st.markdown("""
This document outlines the TRACE pipeline for generating low-dimensional embeddings 
from human fMRI data across multiple datasets and anatomical resolutions.
""")

st.markdown("---")

st.subheader("1. Data Acquisition & Resolution")

tab1, tab2 = st.tabs(["Algonauts (Volumetric)", "HCPTRT (Surface/CIFTI)"])

with tab1:
    st.markdown("""
    - **Source**: Algonauts 2025 naturalistic movie dataset
    - **Resolution**: MNI152 Volumetric (2mm/3mm)
    - **Parcellation**: Schaefer 1000 (7 networks)
    - **Loader**: `AlgonautsLoader` (HDF5 based)
    """)

with tab2:
    st.markdown("""
    - **Source**: HCP Test-Retest Dataset
    - **Resolution**: **CIFTI Grayordinates** (91k vertices/voxels)
    - **Parcellation**: Multi-atlas support (MMP, Cole-Anticevic, Yeo)
    - **Loader**: `HCPTRTLoader` (Direct `.dtseries.nii` loading)
    - **Denoising**: 24 Motion Regressors + CSF/White Matter Denoising
    """)

st.markdown("---")

st.subheader("2. Universal Functional Fingerprinting (HCPTRT)")

st.markdown("""
The core methodology for establishing a universal brain representation involves **Horizontal Signal Stacking**.
""")

st.info("""
**Cross-Task Stacking Process**:
1. **Task Selection**: Motor, Gambling, Working Memory, Social, Emotion, and Resting State.
2. **Temporal Concatenation**: Signals from all tasks are concatenated horizontally for each parcel.
3. **Identity Extraction**: Dimensionality reduction (UMAP) extracts the core features that are invariant across these tasks.
4. **Validation**: We confirm that parcels from the same anatomical region cluster together despite the diverse cognitive demands of the stacked signal.
""")

st.markdown("---")

st.subheader("2.5 Centralized Lobe Mapping (`utils/loaders/parcel_maps.py`)")

st.markdown("""
The `parcel_maps.py` module provides a unified mapping system for region-to-lobe classification across all supported atlases:

| Lobe | Description |
|------|-------------|
| `occipital` | Primary and association visual cortex |
| `parietal` | Dorsal visual, attention, somatosensory association |
| `temporal` | Lateral temporal cortex, hippocampus, amygdala |
| `prefrontal` | Prefrontal cortex, default-mode nodes |
| `somatomotor` | Primary motor and somatosensory cortex |
| `insular` | Insular and opercular cortex, salience network |
| `cingulate` | Anterior and posterior cingulate cortex |
| `orbitofrontal` | Orbitofrontal cortex, limbic network nodes |
| `basal_ganglia` | Striatum (caudate, putamen, accumbens), pallidum |
| `diencephalon` | Thalamus and hypothalamus |
| `cerebellum` | Cerebellar cortex and deep nuclei |
| `brainstem` | Brainstem structures |
""")

st.markdown("---")

st.subheader("3.1 CLI Preprocessing (`main.py`)")

st.markdown("""
Batch preprocessing for HCPTRT data via command-line interface:

```bash
# Preprocess HCPTRT data for subject 01
python main.py preprocessing hcptrt 01

# Preprocess for specific subject
python main.py preprocessing hcptrt sub-03
```

The CLI script reads configuration from `configs/configs.yaml` and `configs/dirs.yaml`, processes each task-session-run combination, and saves X (numpy array) and Y (DataFrame with lobe/structure_type metadata) to `dataset/hcptrt/`.
""")

st.markdown("---")

st.subheader("3. Comparative Atlas Architecture")

st.markdown("""
To ensure the TRACE framework is robust to anatomical definitions, we implemented a centralized mapping system in `utils/loaders/parcel_maps.py`.
""")

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("**Glasser MMP**")
    st.caption("360 fine-grained cortical regions. Highest resolution for fingerprinting.")

with col2:
    st.markdown("**Cole-Anticevic**")
    st.caption("Includes subcortical structures. Ideal for cortical-subcortical boundary analysis.")

with col3:
    st.markdown("**Schaefer (Yeo)**")
    st.caption("Standard functional networks. Used for validation against literature.")

st.markdown("---")

st.subheader("4. TRACE Contrastive Learning Status")

st.markdown("""
**Current Strategy**:
- **Positive Pairs**: Generated by averaging across stacked task subsets or test-retest runs.
- **Negative Pairs**: Other brain regions within the same task-stack.
- **Embedding**: Learning a non-linear manifold that preserves functional identity.
""")

st.markdown("---")

st.header("Current Project Status")

st.success("Milestone: Multi-atlas pipeline and Cross-task validation complete.")

st.markdown("""
| Component | Status | Target Dataset |
|----------|--------|----------------|
| Algonauts Loader Architecture | ✅ Complete | Algonauts |
| HCPTRT Loader Architecture | ✅ Complete | HCPTRT |
| Cross-Task Signal Stacking | ✅ Validated | HCPTRT |
| Surface-Based Parcellation | ✅ Complete | HCPTRT |
| Centralized Lobe Mapping | ✅ Complete | Both |
| CLI Preprocessing (`main.py`) | ✅ Complete | HCPTRT |
| TRACE Contrastive Training | 🔄 Initializing | Both |
""")

st.markdown("---")

st.caption("TRACE originally developed for calcium imaging in mice (Singer et al.)")

st.sidebar.markdown("""
**Progress**

Methodology overview for supervisor review.

[Home](../Home)
[Results](../Results)
""")

st.sidebar.page_link("app.py", label="← Back to Home")
